/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: ribot02 (https://sketchfab.com/ribot02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-cyberpunk-computer-screens-6fbdcecb1b1e4f41947b4c03b5eed8f9
Title: retro cyberpunk computer screens
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  
  const modelref = useRef()

  useFrame((state, delta) =>{
    modelref.current.rotation.z += delta/8
    
  })
  

  return (
    <group {...props} dispose={null}>
      <group ref={modelref} rotation={[-Math.PI / 2, 0, Math.PI ]}>
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_2.geometry} material={materials.Holzverkleidung} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_3.geometry} material={materials.GlowLampBlue} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_4.geometry} material={materials.HolzverkleidungDark} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_5.geometry} material={materials.blackScreen} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_6.geometry} material={materials.metallArm} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_7.geometry} material={materials.monitoHuelle} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_8.geometry} material={materials.monitoHuelle2} />
        <mesh position = {[1.5,-1,-1]} geometry={nodes.Object_9.geometry} material={materials.monitoHuelle2dark} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
