/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rindir (https://sketchfab.com/rindir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-head-bust-2578313d54e043da9b59b6077debc714
Title: Low Poly Head Bust
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_0.geometry}
          material={materials['Scene_-_Root']}
          position={[0, 0.06, 0.584]}
          scale={0.255}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
