/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
Title: Low Poly Planet Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('../../../public/Earth/scene.gltf')
  const modelref = useRef()

  useFrame((state, delta) =>{
    modelref.current.rotation.z += delta/8
    modelref.current.rotation.y += delta/8
  })

  return (
    <group position={[-0.25, -1.1, 0]} ref={modelref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_Planet_0.geometry}
        material={materials.Planet}
        position={[0, 0, 0.066]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('../../../public/Earth/scene.gltf')